### ISSUE TITLE
Add Functionality to Identify and Display Player Status and Blockers

### ISSUE THREAD

**Issue by maskedalligator** [Woodmaninator/StoryWeaverDiscordBot#9]
The current game logic lacks an easy way to query the real-time status of all players and identify blockers in the game flow. To address this, we propose adding two new bot commands:

1. **`!status`**: Provides an overview of the game state and participants' progress.
2. **`!blocking`**: Identifies players causing delays in the game and highlights the required actions.

---

##### **1. General Status Command (`!status`)**
Provides a comprehensive view of the current game state:
- Displays the game's phase (e.g., Lobby Open, Game Running, Game Over).
- Lists all participants with the following details:
  - **Progress**: Number of completed story parts versus the total rounds.
  - **Status**: Whether the player can write (`userCanWrite`) or is waiting for input.

**Example Output:**
```
Game Status:
- Phase: Game Running
- Participants:
  - Player1: Can write (Progress: 2/5)
  - Player2: Waiting for input from Player1 (Progress: 2/5)
  - Player3: Waiting for input from Player2 (Progress: 1/5)
```

---

##### **2. Blocking Status Command (`!blocking`)**
Focuses on identifying delays in the game:
- Highlights participants blocking the game flow.
- Describes the pending action (e.g., "needs to complete part 2 of the story").
- Provides actionable feedback, such as notifying the blocking participant.

**Example Output:**
```
Blocking Status:
- Player2 is blocking the game (needs to complete part 2/5).
- Notify Player2 to proceed.
```

---

#### **Implementation Plan**
1. **Add a new method in `StoryWeaverInstance`:**
   - **For `!status`:** Traverse participants and check their progress and writing status.
   - **For `!blocking`:** Identify the first participant causing delays by analyzing `userCanWrite` and `stories`.

2. **Modify `StoryWeaverManager`:**
   - Handle the new commands:
     - **`!status`:** Fetches the game state and sends it to the user.
     - **`!blocking`:** Highlights blocking participants and their pending actions.

3. **Security and Access:**
   - Ensure only the game creator or participants can use these commands.

---

#### **Impact**
- Enhances transparency for all participants during gameplay.
- Reduces frustration by enabling quick identification of blockers.
- Improves gameplay flow by helping resolve delays efficiently.

---

#### **References**
The following files will need to be updated:
- **`StoryWeaverManager.java`**: Add command handling for `!status` and `!blocking`.
- **`StoryWeaverInstance.java`**: Implement methods for calculating and formatting player statuses.

---

#### **Acceptance Criteria**
- [ ] **`!status`** displays the current state of the game, including progress and permissions.
- [ ] **`!blocking`** identifies delays and provides actionable suggestions.
- [ ] Commands are accessible only to authorized users.
- [ ] The functionality is documented and tested.
